version: "10.0"
services:
  service:
    image: "my_image:latest"
    command: "python3 /usr/src/app/main.py"
    environment:
      - TOKEN=${TOKEN}
  shit_box:
    image: "python:3"
networks:
   default:
     name: bridge-nerwork
     external: true
