version: "10.0"
services:
  service:
    image: "my_image:latest"
    command: "python3 /usr/src/app/main.py"
    environment:
      - API_TOKEN='5938594218:AAGgcU-veWApPiRUOImEojEPXb_VuPKx_2o'
  shit_box:
    image: "python:3"
networks:
   default:
     name: bridge-nerwork
     external: true
